#index:
#    path: /
#    controller: App\Controller\DefaultController::index



translation_test:
  path:     /{_locale}/traduction/{name}
  defaults:
    _controller: App\Controller\TranslationController::translationAction

translation_test1:
  path:     /traduction/{name}
  defaults:
    _controller: App\Controller\TranslationController::translationAction


security_login:
    path: /login
    controller: App\Controller\SecurityController::login

login_check:
    path: /login_check

app_logout:
    path: /logout

user_registration:
    path: /register
    controller: App\Controller\RegistrationController:registerAction

app_home:
    path: /
    controller: App\Controller\PersoController::indexAction


app_work_add:
    path: /work/add
    controller: App\Controller\WorkController::addAction

app_work_details:
    path: /work/{id}
    controller: App\Controller\WorkController::viewAction

app_work_edit:
    path: /work/edit/{id}
    controller: App\Controller\WorkController::editAction

app_work_delete:
    path: /work/delete/{id}
    controller: App\Controller\WorkController::deleteAction


app_character_addByOeuvre:
    path: /character/addByWk/{id}
    controller: App\Controller\PersoController::addByWkAction

app_character_add:
    path: /character/add
    controller: App\Controller\PersoController::addAction

app_character_details:
    path: /character/{id}
    controller: App\Controller\PersoController::viewAction
    requirements:
            id:  \d+

app_character_delete:
    path: /character/delete/{id}
    controller: App\Controller\PersoController::deleteAction
    requirements:
            id:  \d+

app_character_edit:
    path: /character/edit/{id}
    controller: App\Controller\PersoController::editAction
    requirements:
            id:  \d+

app_character_addCom:
    path: /character/edit/com/{id}
    controller: App\Controller\PersoController::addComAction
    requirements:
                id:  \d+


app_com_delete:
    path: /character/delete/com/{id}
    controller: App\Controller\PersoController::deleteComAction
    requirements:
           id:  \d+

app_category_add:
    path: /category/add
    controller: App\Controller\CategoryController::addAction