#index:
#    path: /
#    controller: App\Controller\DefaultController::index


translation_test:
  path:     /{_locale}/traduction/{name}
  defaults:
    _controller: App\Controller\TranslationController::translationAction

translation_test1:
  path:     /traduction/{name}
  defaults:
    _controller: App\Controller\TranslationController::translationAction


security_login:
    path: /{_locale}/login
    controller: App\Controller\SecurityController::login

login_check:
    path: /{_locale}/login_check

app_logout:
    path: /{_locale}/logout

user_registration:
    path: /{_locale}/register
    controller: App\Controller\RegistrationController:registerAction

app_home:
    path: /{_locale}/
    controller: App\Controller\PersoController::indexAction


app_work_add:
    path: /{_locale}/work/add
    controller: App\Controller\WorkController::addAction

app_work_details:
    path: /{_locale}/work/{id}
    controller: App\Controller\WorkController::viewAction

app_work_edit:
    path: /{_locale}/work/edit/{id}
    controller: App\Controller\WorkController::editAction

app_work_delete:
    path: /{_locale}/work/delete/{id}
    controller: App\Controller\WorkController::deleteAction


app_article_add:
    path: /{_locale}/article/add
    controller: App\Controller\ArticleController::addAction

app_character_addByOeuvre:
    path: /{_locale}/character/addByWk/{id}
    controller: App\Controller\PersoController::addByWkAction

app_character_add:
    path: /{_locale}/character/add
    controller: App\Controller\PersoController::addAction

app_character_details:
    path: /{_locale}/character/{id}
    controller: App\Controller\PersoController::viewAction
    requirements:
            id:  \d+

app_character_delete:
    path: /{_locale}/character/delete/{id}
    controller: App\Controller\PersoController::deleteAction
    requirements:
            id:  \d+

app_character_edit:
    path: /{_locale}/character/edit/{id}
    controller: App\Controller\PersoController::editAction
    requirements:
            id:  \d+

app_character_addCom:
    path: /{_locale}/character/edit/com/{id}
    controller: App\Controller\PersoController::addComAction
    requirements:
                id:  \d+


app_com_delete:
    path: /{_locale}/character/delete/com/{id}
    controller: App\Controller\PersoController::deleteComAction
    requirements:
           id:  \d+

app_category_add:
    path: /{_locale}/category/add
    controller: App\Controller\CategoryController::addAction